# Generated by Django 4.2 on 2023-04-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="name")),
            ],
            options={
                "verbose_name": "Категория",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="delievery",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=2, max_digits=8
                    ),
                ),
                ("type_name", models.CharField(db_column="type_name")),
            ],
            options={
                "verbose_name": "Доставка",
                "db_table": "delievery",
            },
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.EmailField(db_column="email", max_length=254, unique=True),
                ),
                ("phone", models.BigIntegerField(db_column="phone", unique=True)),
                ("adress", models.CharField(db_column="adress")),
            ],
            options={
                "verbose_name": "Пользователь",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("amt", models.IntegerField(db_column="amt")),
                ("name", models.CharField(db_column="name")),
                (
                    "description",
                    models.CharField(db_column="description", max_length=1000),
                ),
                (
                    "category_id",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "db_table": "product",
            },
        ),
        migrations.CreateModel(
            name="order_items",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("order_id", models.IntegerField(db_column="order_id")),
                ("quantity", models.IntegerField(db_column="quantity")),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now_add=True, db_column="date")),
                (
                    "delievery_id",
                    models.ForeignKey(
                        db_column="delievery_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.delievery",
                    ),
                ),
                (
                    "order_items_id",
                    models.ForeignKey(
                        db_column="order_items_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.order_items",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "db_table": "order",
            },
        ),
    ]
